# Generated by Django 5.2.17 on 2026-09-10 22:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attempts', '0005_attemptevent_examattempt_answer_revision_and_more'),
        ('exams', '0005_questiontag_examsettings_allow_unanswered_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('exam_published', 'Exam published'), ('exam_started', 'Exam started'), ('exam_ended', 'Exam ended'), ('attempt_submitted', 'Attempt submitted'), ('grading_required', 'Answers waiting for grading'), ('grading_completed', 'Manual grading completed'), ('result_published', 'Result published')], db_index=True, max_length=32)),
                ('title', models.CharField(max_length=200)),
                ('body', models.CharField(blank=True, max_length=500)),
                ('link', models.CharField(blank=True, max_length=300)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('dedupe_key', models.CharField(blank=True, max_length=140)),
                ('attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='attempts.examattempt')),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='exams.exam')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['recipient', 'is_read', '-created_at'], name='notificatio_recipie_684eac_idx'), models.Index(fields=['recipient', 'kind'], name='notificatio_recipie_41b9e1_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('dedupe_key', ''), _negated=True), fields=('recipient', 'dedupe_key'), name='unique_deduped_notification_per_recipient')],
            },
        ),
    ]
