"use client";

import Link from "next/link";
import { ArrowLeft, ClipboardCheck, Clock3, FilePlus2, FileText, ListChecks, UsersRound } from "lucide-react";
import { useCallback, useEffect, useMemo, useState } from "react";
import { resultsApi } from "@/lib/api/results";
import { apiErrorMessage } from "@/lib/api/client";
import type { ApiTeacherOverviewDto } from "@/lib/api/dtos";
import { PageContainer, PageHeader } from "@/components/layout/page-header";
import { PageTransition } from "@/components/shared/page-transition";
import { ExamListCard } from "@/components/dashboard/exam-list-card";
import { StatCard } from "@/components/dashboard/stat-card";
import { EmptyState } from "@/components/shared/empty-state";
import { ExamCalendar } from "@/components/shared/exam-calendar";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import { useTeacherExams } from "@/hooks/use-teacher-exams";
import { useAuthStore } from "@/lib/state/auth-store";
import { toPersianNumber } from "@/lib/utils";

export default function TeacherDashboardPage() {
  const { exams, loading, initialized } = useTeacherExams(); const user = useAuthStore((state) => state.user); const [overview, setOverview] = useState<ApiTeacherOverviewDto | null>(null); const [overviewError, setOverviewError] = useState<string | null>(null);
  // The greeting follows the school's own timezone rather than a fixed "good morning".
  const greeting = useMemo(() => {
    const parts = new Intl.DateTimeFormat("en-GB", { timeZone: "Asia/Tehran", hour: "2-digit", hourCycle: "h23" }).formatToParts(new Date());
    const hour = Number(parts.find((part) => part.type === "hour")?.value ?? "12");
    return hour < 12 ? "صبح بخیر" : hour < 17 ? "روز بخیر" : "عصر بخیر";
  }, []);
  const reloadOverview = useCallback(() => { setOverviewError(null); void resultsApi.teacherOverview().then(setOverview).catch((reason) => setOverviewError(apiErrorMessage(reason, "دریافت آمار انجام نشد."))); }, []);
  useEffect(() => { reloadOverview(); }, [reloadOverview]);
  const active = exams.filter((exam) => exam.status === "active"); const scheduled = exams.filter((exam) => exam.status === "scheduled"); const drafts = exams.filter((exam) => exam.status === "draft"); const completed = exams.filter((exam) => exam.status === "completed"); const recent = exams.filter((exam) => exam.status !== "archived").slice(0, 3);
  return <PageTransition><PageContainer><PageHeader eyebrow="فضای آموزگار" title={`${greeting}، ${user?.fullName || "آموزگار"}`} description="وضعیت آزمون‌ها، مشارکت‌ها و صف تصحیح بر پایهٔ داده‌های واقعی کلاس شماست." breadcrumbs={[{ label: "آموزگار" }, { label: "نمای کلی" }]} action={<Button asChild><Link href="/teacher/exams/create"><FilePlus2 className="h-4 w-4"/>ساخت آزمون</Link></Button>}/>{loading && !initialized ? <DashboardSkeleton/> : <><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><StatCard icon={FileText} label="کل آزمون‌ها" value={toPersianNumber(exams.filter((exam) => exam.status !== "archived").length)} detail="در فضای آموزشی شما" tone="indigo"/><StatCard icon={Clock3} label="در حال برگزاری" value={toPersianNumber(active.length)} detail="آزمون فعال" tone="teal"/><StatCard icon={ListChecks} label="پیش‌نویس‌ها" value={toPersianNumber(drafts.length)} detail="آمادهٔ تکمیل" tone="amber"/><StatCard icon={ClipboardCheck} label="نیازمند تصحیح" value={toPersianNumber(overview?.pending_manual_grading_count ?? 0)} detail="پاسخ‌های متنی" tone="violet"/><StatCard icon={UsersRound} label="دانش‌آموزان مشارکت‌کننده" value={toPersianNumber(overview?.participant_count ?? 0)} detail="بر اساس تلاش واقعی" tone="indigo"/></div><div className="mt-6 grid gap-6 xl:grid-cols-[1.35fr_.85fr]"><section><div className="mb-4 flex items-center justify-between"><div><h2 className="font-black">آزمون‌های پیش‌رو</h2><p className="mt-1 text-xs text-muted-foreground">برنامهٔ این هفته و موارد نیازمند توجه.</p></div><Button asChild variant="ghost" size="sm"><Link href="/teacher/exams">همه آزمون‌ها <ArrowLeft className="h-3.5 w-3.5"/></Link></Button></div>{scheduled.length ? <div className="grid gap-3">{scheduled.map((exam) => <ExamListCard key={exam.id} exam={exam} role="teacher"/>)}</div> : <EmptyState title="آزمون پیش‌رویی ندارید" description="برای کلاس خود یک ارزیابی جدید زمان‌بندی کنید." icon={Clock3} action={{ label: "ساخت آزمون", onClick: () => window.location.assign("/teacher/exams/create") }}/>}</section><aside className="space-y-6"><Card><CardHeader><CardTitle>اقدام سریع</CardTitle><CardDescription>مسیرهای پرتکرار فضای کاری</CardDescription></CardHeader><CardContent className="grid gap-2"><Button asChild variant="secondary" className="justify-between"><Link href="/teacher/exams/create">ساخت آزمون جدید <FilePlus2 className="h-4 w-4"/></Link></Button><Button asChild variant="secondary" className="justify-between"><Link href="/teacher/questions">مدیریت بانک سؤال <ListChecks className="h-4 w-4"/></Link></Button><Button asChild variant="secondary" className="justify-between"><Link href="/teacher/results">بررسی و انتشار نتایج <ArrowLeft className="h-4 w-4"/></Link></Button></CardContent></Card><Card><CardHeader><CardTitle>وضعیت مشارکت و عملکرد</CardTitle><CardDescription>همهٔ عدد‌ها از تجمیع تلاش‌های واقعی شماست.</CardDescription></CardHeader><CardContent>
              <div className="grid grid-cols-2 gap-3">
                <DashboardMetric label="تلاش‌ها" value={`${toPersianNumber(overview?.finalized_attempt_count ?? 0)} از ${toPersianNumber(overview?.attempt_count ?? 0)}`} hint={`${toPersianNumber(overview?.participant_count ?? 0)} دانش‌آموز مشارکت کرده‌اند`}/>
                <DashboardMetric label="نرخ تکمیل" value={overview ? `${toPersianNumber(overview.completion_rate)}٪` : "—"} hint="تلاش‌های نهایی‌شده از کل تلاش‌های شروع‌شده"/>
                <DashboardMetric label="میانگین درصد" value={overview?.average_percentage !== null && overview?.average_percentage !== undefined ? `${toPersianNumber(Math.round(overview.average_percentage))}٪` : "—"} hint={`بر پایهٔ ${toPersianNumber(overview?.graded_result_count ?? 0)} نتیجهٔ نمره‌گرفته`}/>
                <DashboardMetric label="نرخ قبولی" value={overview?.pass_rate !== null && overview?.pass_rate !== undefined ? `${toPersianNumber(overview.pass_rate)}٪` : "حدنصاب ندارید"} hint={overview?.verdict_count ? `${toPersianNumber(overview.passed_count ?? 0)} قبول از ${toPersianNumber(overview.verdict_count)} نتیجه` : "برای آزمون‌ها حدنصاب قبولی تعیین کنید"}/>
              </div>
              <div className="mt-4 h-2 overflow-hidden rounded-full bg-muted" role="progressbar" aria-valuemin={0} aria-valuemax={100} aria-valuenow={overview?.completion_rate ?? 0} aria-label="نرخ تکمیل آزمون‌ها"><div className="h-full rounded-full bg-emerald-500" style={{ width: `${overview?.completion_rate ?? 0}%` }}/></div>
              <p className="mt-2 text-[11px] text-muted-foreground">{overview?.pending_manual_answer_count ? `${toPersianNumber(overview.pending_manual_answer_count)} پاسخ برای نمرهٔ دستی باقی مانده است.` : "پاسخ در انتظار تصحیح ندارید."}</p>
            </CardContent></Card></aside></div><div className="mt-6 grid gap-6 xl:grid-cols-[1.15fr_.85fr]"><Card><CardHeader><CardTitle>خلاصهٔ آزمون‌ها</CardTitle><CardDescription>وضعیت‌های ثبت‌شده در سرور</CardDescription></CardHeader><CardContent><div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{[{label:"فعال",value:active.length,tone:"text-emerald-600"},{label:"زمان‌بندی",value:scheduled.length,tone:"text-primary"},{label:"پایان‌یافته",value:completed.length,tone:"text-violet-600"},{label:"پیش‌نویس",value:drafts.length,tone:"text-amber-600"}].map((item) => <div className="rounded-2xl bg-muted/60 p-4" key={item.label}><p className={`text-2xl font-black ${item.tone}`}>{toPersianNumber(item.value)}</p><p className="mt-1 text-xs font-bold text-muted-foreground">{item.label}</p></div>)}</div></CardContent></Card><ExamCalendar exams={exams.filter((exam) => exam.status !== "archived")} role="teacher"/>
              <Card><CardHeader><CardTitle>فعالیت‌های اخیر</CardTitle><CardDescription>آخرین تلاش‌های واقعی دانش‌آموزان</CardDescription></CardHeader><CardContent>{overviewError ? <p className="flex flex-wrap items-center gap-2 text-xs text-destructive">{overviewError}<Button size="sm" variant="outline" onClick={reloadOverview}>تلاش دوباره</Button></p> : overview?.recent_activity.length ? <div className="space-y-1">{overview.recent_activity.map((activity) => <div key={activity.id} className="flex items-center gap-3 rounded-xl p-2.5"><span className={`h-2.5 w-2.5 rounded-full ${activity.status === "in_progress" ? "bg-primary" : "bg-emerald-500"}`}/><div className="min-w-0 flex-1"><p className="text-xs font-bold">{activity.student_name} · {activity.title}</p><p className="mt-1 text-[11px] text-muted-foreground">{activity.status === "in_progress" ? "در حال پاسخ‌گویی" : "تلاش نهایی شده"}</p></div><span className="whitespace-nowrap text-[10px] font-bold text-muted-foreground">{new Intl.DateTimeFormat("fa-IR", { hour: "2-digit", minute: "2-digit" }).format(new Date(activity.at))}</span></div>)}</div> : <p className="text-sm text-muted-foreground">هنوز تلاشی ثبت نشده است.</p>}</CardContent></Card></div><section className="mt-6"><div className="mb-4 flex items-center justify-between"><div><h2 className="font-black">آزمون‌های اخیر</h2><p className="mt-1 text-xs text-muted-foreground">آخرین آزمون‌های ساخته‌شده یا به‌روز‌شده.{overview?.recently_completed_exams?.length ? ` ${toPersianNumber(overview.recently_completed_exams.length)} آزمون اخیراً پایان یافته است.` : ""}</p></div><Button asChild variant="ghost" size="sm"><Link href="/teacher/exams">مدیریت آزمون‌ها <ArrowLeft className="h-3.5 w-3.5"/></Link></Button></div><div className="grid gap-3 lg:grid-cols-3">{recent.map((exam) => <ExamListCard key={exam.id} exam={exam} role="teacher"/>)}</div></section></>}</PageContainer></PageTransition>;
}
function DashboardSkeleton() { return <><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5">{Array.from({ length: 5 }).map((_, index) => <Card className="p-5" key={index}><Skeleton className="h-10 w-10"/><Skeleton className="mt-5 h-8 w-16"/><Skeleton className="mt-3 h-4 w-28"/></Card>)}</div><div className="mt-6 grid gap-6 xl:grid-cols-2"><Card className="h-80"><Skeleton className="m-6 h-64"/></Card><Card className="h-80"><Skeleton className="m-6 h-64"/></Card></div></>; }

function DashboardMetric({ label, value, hint }: { label: string; value: string; hint: string }) {
  return <div className="rounded-2xl bg-muted/55 p-3"><p className="text-[11px] font-bold text-muted-foreground">{label}</p><p className="mt-1 text-lg font-black">{value}</p><p className="mt-1 text-[10px] leading-4 text-muted-foreground">{hint}</p></div>;
}
