# Generated by Django 5.2.17 on 2026-09-11 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('admin', 'Administrator'), ('school_admin', 'School administrator')], db_index=True, default='student', max_length=20),
        ),
    ]
