# Generated by Django 5.2.17 on 2026-09-06 08:59

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('subject', models.CharField(db_index=True, max_length=150)),
                ('grade', models.CharField(blank=True, max_length=100)),
                ('class_name', models.CharField(blank=True, max_length=100)),
                ('instructions', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('active', 'Active'), ('completed', 'Completed'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('duration_minutes', models.PositiveIntegerField()),
                ('total_marks', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('start_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='ExamSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allow_previous_questions', models.BooleanField(default=True)),
                ('randomize_questions', models.BooleanField(default=False)),
                ('result_visibility', models.CharField(choices=[('immediate', 'Immediately after submission'), ('pending', 'After teacher review'), ('hidden', 'Manually published')], default='pending', max_length=20)),
                ('show_correct_answers', models.BooleanField(default=False)),
                ('max_attempts', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'verbose_name_plural': 'Exam settings',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('multiple_choice', 'Multiple choice'), ('multiple_answer', 'Multiple answer'), ('true_false', 'True / False'), ('short_answer', 'Short answer'), ('written', 'Written answer')], db_index=True, max_length=30)),
                ('text', models.TextField()),
                ('instructions', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField()),
                ('marks', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=7)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('explanation', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=1000)),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ('order',),
            },
        ),
    ]
