# Generated by Django 5.2.17 on 2026-09-10 12:33

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_exam_status_before_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsettings',
            name='passing_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
    ]
