# Generated by Django 5.2.17 on 2026-09-10 18:48

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_examsettings_passing_percentage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=60)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='examsettings',
            name='allow_unanswered',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='examsettings',
            name='randomize_options',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='copied_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copies', to='exams.question'),
        ),
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], db_index=True, default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='question',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='exam',
            constraint=models.CheckConstraint(condition=models.Q(('duration_minutes__gte', 1)), name='exam_duration_positive'),
        ),
        migrations.AddConstraint(
            model_name='exam',
            constraint=models.CheckConstraint(condition=models.Q(('end_at__isnull', True), ('start_at__isnull', True), ('end_at__gt', models.F('start_at')), _connector='OR'), name='exam_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='questionoption',
            constraint=models.CheckConstraint(condition=models.Q(('order__gte', 1)), name='option_order_positive'),
        ),
        migrations.AddField(
            model_name='questiontag',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_tags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='questions', to='exams.questiontag'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['type', 'difficulty'], name='exams_quest_type_e77f38_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['is_archived', 'difficulty'], name='exams_quest_is_arch_679e4b_idx'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.CheckConstraint(condition=models.Q(('order__gte', 1)), name='question_order_positive'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.CheckConstraint(condition=models.Q(('marks__gte', Decimal('0'))), name='question_marks_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='questiontag',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('teacher'), name='unique_tag_name_per_teacher'),
        ),
    ]
