# Generated by Django 5.2.17 on 2026-09-11 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_questiontag_examsettings_allow_unanswered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsettings',
            name='question_layout',
            field=models.CharField(choices=[('paged', 'One question per page'), ('single_page', 'All questions on one page')], default='paged', max_length=12),
        ),
    ]
