# Generated by Django 5.2.17 on 2026-09-12 11:35

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0009_examsettings_result_detail'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='question',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_questions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready')], default='ready', max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exams.exam'),
        ),
        migrations.CreateModel(
            name='QuestionFolder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='exams.questionfolder')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_folders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='question',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='exams.questionfolder'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['owner', 'folder'], name='exams_quest_owner_i_c3c5b9_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['owner', 'category'], name='exams_quest_owner_i_febd18_idx'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(condition=models.Q(('exam__isnull', True), models.Q(('content_hash', ''), _negated=True), models.Q(('owner__isnull', True), _negated=True)), fields=('owner', 'content_hash'), name='unique_bank_content_per_teacher', violation_error_message='Your bank already holds an identical question.'),
        ),
        migrations.AddConstraint(
            model_name='questionfolder',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('parent'), models.F('teacher'), name='unique_folder_name_per_parent'),
        ),
    ]
