# Generated by Django 5.2.17 on 2026-09-12 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0010_question_category_question_owner_question_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsettings',
            name='block_copy_paste',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='examsettings',
            name='integrity_policy',
            field=models.CharField(choices=[('off', 'Off'), ('observe', 'Record only'), ('enforce', 'Record and enforce')], default='off', max_length=12),
        ),
        migrations.AddField(
            model_name='examsettings',
            name='lock_to_one_device',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='examsettings',
            name='max_tab_switches',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='examsettings',
            name='require_fullscreen',
            field=models.BooleanField(default=False),
        ),
    ]
