# Generated by Django 5.2.17 on 2026-09-06 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attempts', '0002_initial'),
        ('exams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='examattempt',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='attempts.examattempt'),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_answers', to='exams.question'),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='selected_options',
            field=models.ManyToManyField(blank=True, related_name='selected_by_answers', to='exams.questionoption'),
        ),
        migrations.AddIndex(
            model_name='examattempt',
            index=models.Index(fields=['student', 'status'], name='attempts_ex_student_19397b_idx'),
        ),
        migrations.AddIndex(
            model_name='examattempt',
            index=models.Index(fields=['exam', 'status'], name='attempts_ex_exam_id_50fffa_idx'),
        ),
        migrations.AddIndex(
            model_name='examattempt',
            index=models.Index(fields=['exam', 'student'], name='attempts_ex_exam_id_8d57b2_idx'),
        ),
        migrations.AddConstraint(
            model_name='examattempt',
            constraint=models.UniqueConstraint(fields=('exam', 'student', 'attempt_number'), name='unique_exam_student_attempt_number'),
        ),
        migrations.AddIndex(
            model_name='studentanswer',
            index=models.Index(fields=['attempt', 'question'], name='attempts_st_attempt_0bde60_idx'),
        ),
        migrations.AddIndex(
            model_name='studentanswer',
            index=models.Index(fields=['question'], name='attempts_st_questio_c66343_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentanswer',
            constraint=models.UniqueConstraint(fields=('attempt', 'question'), name='unique_answer_per_attempt_question'),
        ),
    ]
