# Generated by Django 5.2.17 on 2026-09-06 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examattempt',
            name='question_order',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
