# Generated by Django 5.2.17 on 2026-09-10 18:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0004_examattempt_question_order'),
        ('exams', '0004_examsettings_passing_percentage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttemptEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('session_switch', 'Another browser session took over'), ('tab_hidden', 'Exam tab hidden'), ('tab_visible', 'Exam tab visible again'), ('disconnected', 'Connection lost'), ('reconnected', 'Connection restored'), ('auto_submitted', 'Submitted when the timer expired'), ('exam_closed', 'Finalized because the teacher ended the exam'), ('stale_write_rejected', 'Out-of-date save request rejected')], db_index=True, max_length=32)),
                ('detail', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='examattempt',
            name='answer_revision',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='client_session',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='option_order',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='session_switch_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='examattempt',
            index=models.Index(fields=['status', 'expires_at'], name='attempts_ex_status_d76f7f_idx'),
        ),
        migrations.AddConstraint(
            model_name='examattempt',
            constraint=models.CheckConstraint(condition=models.Q(('attempt_number__gte', 1)), name='attempt_number_positive'),
        ),
        migrations.AddField(
            model_name='attemptevent',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='attempts.examattempt'),
        ),
        migrations.AddIndex(
            model_name='attemptevent',
            index=models.Index(fields=['attempt', 'kind'], name='attempts_at_attempt_9a6f11_idx'),
        ),
        migrations.AddIndex(
            model_name='attemptevent',
            index=models.Index(fields=['attempt', 'created_at'], name='attempts_at_attempt_48f60d_idx'),
        ),
    ]
