# Generated by Django 5.2.17 on 2026-09-11 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0005_attemptevent_examattempt_answer_revision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examattempt',
            name='answer_frontier',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attemptevent',
            name='kind',
            field=models.CharField(choices=[('session_switch', 'Another browser session took over'), ('tab_hidden', 'Exam tab hidden'), ('tab_visible', 'Exam tab visible again'), ('disconnected', 'Connection lost'), ('reconnected', 'Connection restored'), ('auto_submitted', 'Submitted when the timer expired'), ('exam_closed', 'Finalized because the teacher ended the exam'), ('stale_write_rejected', 'Out-of-date save request rejected'), ('question_locked', 'Edit refused by the no-return rule')], db_index=True, max_length=32),
        ),
    ]
