# Generated by Django 5.2.17 on 2026-09-12 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0006_examattempt_answer_frontier_alter_attemptevent_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='examattempt',
            name='device_signature',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='attemptevent',
            name='kind',
            field=models.CharField(choices=[('session_switch', 'Another browser session took over'), ('tab_hidden', 'Exam tab hidden'), ('tab_visible', 'Exam tab visible again'), ('disconnected', 'Connection lost'), ('reconnected', 'Connection restored'), ('auto_submitted', 'Submitted when the timer expired'), ('exam_closed', 'Finalized because the teacher ended the exam'), ('stale_write_rejected', 'Out-of-date save request rejected'), ('question_locked', 'Edit refused by the no-return rule'), ('copy', 'Copied text out of the exam'), ('cut', 'Cut text inside the exam'), ('paste', 'Pasted text into an answer'), ('fullscreen_enter', 'Fullscreen started'), ('fullscreen_exit', 'Fullscreen left'), ('session_lock_refused', 'Another device was refused the attempt'), ('tab_limit_reached', 'Tab-switch limit reached')], db_index=True, max_length=32),
        ),
    ]
