"use client";

import { AnimatePresence, motion } from "framer-motion";
import { AlertTriangle, ArrowLeft, ArrowRight, CalendarDays, Check, ChevronLeft, Clock3, FileText, ListChecks, Save, Settings2, Sparkles } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import type { Exam, ExamDraft, ExamSettings, ResultVisibility } from "@/lib/types/domain";
import { TeacherQuestionBuilder } from "@/components/teacher/question-builder";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { useTeacherExams } from "@/hooks/use-teacher-exams";
import { useToastStore } from "@/lib/state/toast-store";
import { cn, toPersianNumber } from "@/lib/utils";

const steps = [
  { title: "اطلاعات پایه", description: "مشخصات اصلی آزمون را تنظیم کنید.", icon: FileText },
  { title: "تنظیمات", description: "قواعد تجربهٔ آزمون را مشخص کنید.", icon: Settings2 },
  { title: "سؤال‌ها", description: "سؤال‌ها و نمره‌های آزمون را بسازید.", icon: ListChecks },
  { title: "زمان‌بندی", description: "بازهٔ دسترسی دانش‌آموزان را انتخاب کنید.", icon: CalendarDays },
  { title: "بازبینی", description: "جزئیات را نهایی و منتشر کنید.", icon: Check },
];
const defaultSettings: ExamSettings = { durationMinutes: 45, totalMarks: 0, allowBackNavigation: true, randomizeQuestions: false, showResultImmediately: false, resultVisibility: "pending", showCorrectAnswers: false, attemptLimit: 1, passingScore: 50 };
const emptyDraft = (): ExamDraft => ({ title: "", subject: "زیست‌شناسی", grade: "پایه دوازدهم", className: "تجربی ۲", description: "", instructions: "", settings: defaultSettings, schedule: { startAt: "2026-09-14T08:30", endAt: "2026-09-14T09:30", timezone: "Asia/Tehran" }, questions: [] });
const asDraft = (exam: Exam): ExamDraft => ({ id: exam.id, title: exam.title, subject: exam.subject, grade: exam.grade, className: exam.className, description: exam.description, instructions: exam.instructions ?? "", settings: { ...exam.settings }, schedule: { ...exam.schedule }, questions: exam.questions.map((question) => question.type === "single_choice" || question.type === "multiple_choice" ? { ...question, options: question.options.map((option) => ({ ...option })) } : { ...question }) });

export function ExamCreator({ examId }: { examId?: string }) {
  const router = useRouter();
  const toast = useToastStore((state) => state.push);
  const { exams, loading, detailLoadingId, initialized, error, clearError, saveExam, loadExam } = useTeacherExams();
  const [step, setStep] = useState(0);
  const [draft, setDraft] = useState<ExamDraft>(emptyDraft);
  const [saving, setSaving] = useState<"draft" | "publish" | null>(null);
  const existing = examId ? exams.find((exam) => exam.id === examId) : undefined;
  useEffect(() => { if (examId) void loadExam(examId); }, [examId, loadExam]);
  useEffect(() => { if (existing) setDraft(asDraft(existing)); }, [existing?.id]);
  const totalMarks = useMemo(() => draft.questions.reduce((sum, question) => sum + question.points, 0), [draft.questions]);
  const validation = useMemo(() => validateDraft(draft), [draft]);
  const update = <K extends keyof ExamDraft>(key: K, value: ExamDraft[K]) => setDraft((current) => ({ ...current, [key]: value }));
  const updateSettings = (patch: Partial<ExamSettings>) => setDraft((current) => ({ ...current, settings: { ...current.settings, ...patch } }));
  const updateSchedule = (patch: Partial<ExamDraft["schedule"]>) => setDraft((current) => ({ ...current, schedule: { ...current.schedule, ...patch } }));
  function validateStep(index: number) { return validation.filter((item) => item.step === index); }
  function next() { const errors = validateStep(step); if (errors.length) { toast({ title: "پیش از ادامه، این بخش را کامل کنید", description: errors[0].message, variant: "error" }); return; } setStep((current) => Math.min(current + 1, steps.length - 1)); }
  async function persist(mode: "draft" | "publish") { const errors = validation; if (mode === "publish" && errors.length) { setStep(errors[0].step); toast({ title: "آزمون هنوز آمادهٔ انتشار نیست", description: errors[0].message, variant: "error" }); return; } setSaving(mode); try { const saved = await saveExam({ ...draft, settings: { ...draft.settings, totalMarks } }, mode === "publish" ? "scheduled" : "draft"); toast({ title: mode === "publish" ? "آزمون زمان‌بندی و منتشر شد" : "پیش‌نویس ذخیره شد", description: mode === "publish" ? "دانش‌آموزان در بازهٔ تعیین‌شده به آزمون دسترسی خواهند داشت." : "می‌توانید بعداً این آزمون را تکمیل کنید.", variant: "success" }); router.push(`/teacher/exams/${saved.id}`); } catch { /* Store exposes a recoverable error state below. */ } finally { setSaving(null); } }
  if (examId && !existing && (loading || !initialized || detailLoadingId === examId)) return <BuilderSkeleton/>;
  if (examId && initialized && !existing) return <Card className="p-8 text-center"><h2 className="font-black">آزمون موردنظر پیدا نشد</h2><p className="mt-2 text-sm text-muted-foreground">ممکن است آزمون بایگانی یا حذف شده باشد.</p><Button className="mt-5" onClick={() => router.push("/teacher/exams")}>بازگشت به آزمون‌ها</Button></Card>;
  return <div className="grid gap-6 xl:grid-cols-[250px_minmax(0,1fr)]"><BuilderStepper step={step} onStep={(target) => target <= step && setStep(target)}/><Card className="min-h-[600px]"><CardHeader className="border-b"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="section-label">{examId ? "ویرایش آزمون" : "آزمون جدید"} · گام {toPersianNumber(step + 1)} از {toPersianNumber(steps.length)}</p><CardTitle className="mt-1 text-xl">{steps[step].title}</CardTitle><CardDescription className="mt-1">{steps[step].description}</CardDescription></div>{step < 4 && <Button variant="outline" size="sm" onClick={() => void persist("draft")} disabled={saving !== null}><Save className="h-3.5 w-3.5"/>ذخیره پیش‌نویس</Button>}</div></CardHeader><CardContent className="p-5 sm:p-6"><AnimatePresence mode="wait"><motion.div key={step} initial={{ opacity: 0, x: -8 }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0, x: 8 }} transition={{ duration: .18 }}>{step === 0 && <BasicInformation draft={draft} update={update} errors={validateStep(0)}/>} {step === 1 && <ExamSettingsForm settings={draft.settings} totalMarks={totalMarks} onChange={updateSettings}/>} {step === 2 && <TeacherQuestionBuilder questions={draft.questions} onChange={(questions) => update("questions", questions)}/>} {step === 3 && <ScheduleForm schedule={draft.schedule} onChange={updateSchedule} errors={validateStep(3)}/>} {step === 4 && <ReviewPublish draft={draft} totalMarks={totalMarks} validation={validation}/>}</motion.div></AnimatePresence>{error && <div role="alert" className="mt-5 flex flex-wrap items-center gap-3 rounded-2xl border border-rose-500/20 bg-rose-500/5 p-3 text-xs leading-6 text-rose-800 dark:text-rose-300"><AlertTriangle className="h-4 w-4 shrink-0 text-rose-600"/><span className="flex-1">{error}</span><Button variant="outline" size="sm" onClick={clearError}>بستن</Button></div>}<div className="mt-8 flex flex-wrap items-center justify-between gap-3 border-t pt-5"><Button variant="outline" onClick={() => setStep((current) => Math.max(current - 1, 0))} disabled={step === 0 || saving !== null}><ArrowRight className="h-4 w-4"/>قبلی</Button>{step < steps.length - 1 ? <Button onClick={next} disabled={saving !== null}>ادامه <ArrowLeft className="h-4 w-4"/></Button> : <div className="mr-auto flex flex-wrap gap-2"><Button variant="outline" onClick={() => void persist("draft")} disabled={saving !== null}>{saving === "draft" ? "در حال ذخیره…" : "ذخیره به‌عنوان پیش‌نویس"}</Button><Button onClick={() => void persist("publish")} disabled={saving !== null}>{saving === "publish" ? "در حال انتشار…" : "انتشار آزمون"}<Sparkles className="h-4 w-4"/></Button></div>}</div></CardContent></Card></div>;
}
function BuilderStepper({ step, onStep }: { step: number; onStep: (step: number) => void }) { return <aside className="rounded-2xl border bg-card p-3 shadow-soft"><div className="flex gap-1 overflow-x-auto xl:block xl:space-y-1">{steps.map((item, index) => { const Icon = item.icon; const active = index === step; const complete = index < step; return <button type="button" key={item.title} onClick={() => onStep(index)} disabled={index > step} aria-current={active ? "step" : undefined} className={cn("flex shrink-0 items-center gap-3 rounded-xl px-3 py-2.5 text-right text-xs font-bold transition-colors xl:w-full", active ? "bg-primary/10 text-primary" : complete ? "text-emerald-600 hover:bg-muted" : "text-muted-foreground", index > step && "cursor-not-allowed opacity-60")}><span className={cn("grid h-6 w-6 place-items-center rounded-lg", active ? "bg-primary text-primary-foreground" : complete ? "bg-emerald-500/10" : "bg-muted")}>{complete ? <Check className="h-3.5 w-3.5"/> : <Icon className="h-3.5 w-3.5"/>}</span>{item.title}</button>; })}</div></aside>; }
function BasicInformation({ draft, update, errors }: { draft: ExamDraft; update: <K extends keyof ExamDraft>(key: K, value: ExamDraft[K]) => void; errors: ValidationIssue[] }) { const has = (field: string) => errors.some((item) => item.field === field); return <div className="grid gap-5"><div className="grid gap-5 sm:grid-cols-2"><Field label="عنوان آزمون" required error={has("title") ? "برای آزمون یک عنوان وارد کنید." : undefined}><Input value={draft.title} onChange={(event) => update("title", event.target.value)} placeholder="مثلاً آزمون فصل اول زیست‌شناسی" maxLength={90} aria-invalid={has("title")}/><Counter value={draft.title.length} max={90}/></Field><Field label="درس" required><select value={draft.subject} onChange={(event) => update("subject", event.target.value)} className="h-11 w-full rounded-xl border bg-background px-3 text-sm"><option>زیست‌شناسی</option><option>ریاضی</option><option>شیمی</option><option>فیزیک</option><option>ادبیات فارسی</option></select></Field><Field label="پایه" required><select value={draft.grade} onChange={(event) => update("grade", event.target.value)} className="h-11 w-full rounded-xl border bg-background px-3 text-sm"><option>پایه دهم</option><option>پایه یازدهم</option><option>پایه دوازدهم</option></select></Field><Field label="کلاس" required><select value={draft.className} onChange={(event) => update("className", event.target.value)} className="h-11 w-full rounded-xl border bg-background px-3 text-sm"><option>تجربی ۲</option><option>تجربی ۱</option><option>ریاضی ۱</option><option>انسانی ۱</option></select></Field></div><Field label="توضیح کوتاه" required error={has("description") ? "یک توضیح کوتاه برای دانش‌آموز وارد کنید." : undefined}><Textarea value={draft.description} onChange={(event) => update("description", event.target.value)} placeholder="هدف و محدودهٔ آزمون را در یک یا دو جمله توضیح دهید..." maxLength={280} className="min-h-28" aria-invalid={has("description")}/><Counter value={draft.description.length} max={280}/></Field><Field label="راهنمای دانش‌آموز (اختیاری)"><Textarea value={draft.instructions} onChange={(event) => update("instructions", event.target.value)} placeholder="مثلاً پیش از ارسال، پاسخ‌های خود را مرور کنید." maxLength={500} className="min-h-24"/><Counter value={draft.instructions.length} max={500}/></Field></div>; }
function ExamSettingsForm({ settings, totalMarks, onChange }: { settings: ExamSettings; totalMarks: number; onChange: (patch: Partial<ExamSettings>) => void }) { return <div className="space-y-6"><div className="grid gap-4 sm:grid-cols-3"><Field label="مدت آزمون (دقیقه)" required><div className="relative"><Clock3 className="pointer-events-none absolute right-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground"/><Input type="number" min="5" max="300" value={settings.durationMinutes} onChange={(event) => onChange({ durationMinutes: Math.max(5, Number(event.target.value)) })} className="pr-9"/></div></Field><Field label="نمره کل"><div className="flex h-11 items-center rounded-xl border bg-muted/55 px-3 text-sm font-black text-primary">{toPersianNumber(totalMarks)} نمره</div><p className="mt-1 text-[10px] text-muted-foreground">بر اساس نمرهٔ سؤال‌ها محاسبه می‌شود.</p></Field><Field label="حدنصاب قبولی"><div className="relative"><Input type="number" min="0" max="100" value={settings.passingScore} onChange={(event) => onChange({ passingScore: Math.min(100, Math.max(0, Number(event.target.value))) })}/><span className="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2 text-xs font-bold text-muted-foreground">٪</span></div></Field></div><section><h3 className="text-sm font-black">قوانین پاسخ‌گویی</h3><div className="mt-3 grid gap-3 lg:grid-cols-2"><SettingSwitch label="اجازهٔ بازگشت به سؤال‌ها" description="دانش‌آموز بتواند پاسخ سؤال‌های قبل را مرور کند." checked={settings.allowBackNavigation} onChange={(checked) => onChange({ allowBackNavigation: checked })}/><SettingSwitch label="ترتیب تصادفی سؤال‌ها" description="سؤال‌ها برای هر دانش‌آموز با ترتیب متفاوت نمایش داده شوند." checked={settings.randomizeQuestions} onChange={(checked) => onChange({ randomizeQuestions: checked })}/></div></section><section><h3 className="text-sm font-black">نتیجه و بازخورد</h3><div className="mt-3 grid gap-4 sm:grid-cols-2"><Field label="نمایش نتیجه"><select value={settings.resultVisibility} onChange={(event) => { const value = event.target.value as ResultVisibility; onChange({ resultVisibility: value, showResultImmediately: value === "immediate" }); }} className="h-11 w-full rounded-xl border bg-background px-3 text-sm"><option value="immediate">بلافاصله پس از ارسال</option><option value="pending">پس از بررسی آموزگار</option><option value="hidden">تا زمان انتشار دستی</option></select></Field><Field label="تعداد تلاش مجاز"><select value={settings.attemptLimit} onChange={(event) => onChange({ attemptLimit: Number(event.target.value) })} className="h-11 w-full rounded-xl border bg-background px-3 text-sm"><option value={1}>یک بار</option><option value={2}>دو بار</option><option value={3}>سه بار</option></select></Field></div><div className="mt-3 rounded-2xl border bg-muted/40 p-4 text-xs leading-6 text-muted-foreground">برای حفظ امنیت آزمون، کلید پاسخ و جزئیات تنظیمات تصحیح در نتیجهٔ دانش‌آموز نمایش داده نمی‌شود.</div></section></div>; }
function ScheduleForm({ schedule, onChange, errors }: { schedule: ExamDraft["schedule"]; onChange: (patch: Partial<ExamDraft["schedule"]>) => void; errors: ValidationIssue[] }) { const invalid = errors.some((item) => item.field === "schedule"); return <div className="grid gap-5"><div className="grid gap-5 sm:grid-cols-2"><Field label="تاریخ و ساعت شروع" required><Input type="datetime-local" value={schedule.startAt} onChange={(event) => onChange({ startAt: event.target.value })}/></Field><Field label="تاریخ و ساعت پایان" required error={invalid ? "زمان پایان باید بعد از زمان شروع باشد." : undefined}><Input type="datetime-local" value={schedule.endAt} onChange={(event) => onChange({ endAt: event.target.value })} aria-invalid={invalid}/></Field></div><Field label="منطقه زمانی"><select value={schedule.timezone} onChange={(event) => onChange({ timezone: event.target.value })} className="h-11 w-full rounded-xl border bg-background px-3 text-sm"><option value="Asia/Tehran">تهران (GMT +03:30)</option><option value="Asia/Dubai">دبی (GMT +04:00)</option><option value="Europe/Istanbul">استانبول (GMT +03:00)</option></select></Field><div className="rounded-2xl bg-primary/[.05] p-4 text-xs leading-6 text-muted-foreground"><CalendarDays className="ml-2 inline h-4 w-4 text-primary align-text-bottom"/>دانش‌آموزان فقط در این بازه می‌توانند آزمون را شروع کنند. زمان پاسخ‌گویی هر دانش‌آموز از لحظهٔ شروع او محاسبه می‌شود.</div></div>; }
function ReviewPublish({ draft, totalMarks, validation }: { draft: ExamDraft; totalMarks: number; validation: ValidationIssue[] }) { const complete = validation.length === 0; return <div><div className={cn("flex items-start gap-3 rounded-2xl border p-4 text-sm leading-6", complete ? "border-emerald-500/20 bg-emerald-500/[.06] text-emerald-800 dark:text-emerald-300" : "border-amber-500/25 bg-amber-500/[.08] text-amber-900 dark:text-amber-300")}><span className={cn("grid h-7 w-7 shrink-0 place-items-center rounded-lg", complete ? "bg-emerald-500/15 text-emerald-600" : "bg-amber-500/15 text-amber-600")}>{complete ? <Check className="h-4 w-4"/> : <AlertTriangle className="h-4 w-4"/>}</span><div><b>{complete ? "آزمون آمادهٔ انتشار است" : "چند مورد نیاز به تکمیل دارد"}</b><p className="mt-1 text-xs">{complete ? "تنظیمات، سؤال‌ها و زمان‌بندی با هم سازگار هستند." : validation.map((item) => item.message).join(" · ")}</p></div></div><div className="mt-5 grid gap-3 sm:grid-cols-2">{[{label:"عنوان",value:draft.title || "بدون عنوان"},{label:"کلاس",value:`${draft.grade} · ${draft.className}`},{label:"سؤال‌ها",value:`${toPersianNumber(draft.questions.length)} سؤال`},{label:"نمره کل",value:`${toPersianNumber(totalMarks)} نمره`},{label:"مدت",value:`${toPersianNumber(draft.settings.durationMinutes)} دقیقه`},{label:"بازهٔ برگزاری",value:`${draft.schedule.startAt.replace("T", " · ")} تا ${draft.schedule.endAt.slice(11)}`}].map((item) => <div className="rounded-xl bg-muted/60 p-3" key={item.label}><p className="text-[11px] font-bold text-muted-foreground">{item.label}</p><p className="mt-1 text-sm font-extrabold">{item.value}</p></div>)}</div><div className="mt-5 rounded-2xl border p-4"><h3 className="text-sm font-black">قواعد آزمون</h3><div className="mt-3 grid gap-2 text-xs text-muted-foreground sm:grid-cols-2"><span>• {draft.settings.allowBackNavigation ? "بازگشت به سؤال‌ها مجاز است" : "بازگشت به سؤال‌ها مجاز نیست"}</span><span>• {draft.settings.randomizeQuestions ? "ترتیب سؤال‌ها تصادفی است" : "ترتیب سؤال‌ها ثابت است"}</span><span>• نتیجه: {resultLabel[draft.settings.resultVisibility]}</span><span>• {draft.settings.attemptLimit} تلاش مجاز</span></div></div></div>; }
const resultLabel: Record<ResultVisibility, string> = { immediate: "نمایش فوری", pending: "پس از بررسی", hidden: "انتشار دستی" };
interface ValidationIssue { step: number; field: string; message: string; }
function validateDraft(draft: ExamDraft): ValidationIssue[] { const issues: ValidationIssue[] = []; if (!draft.title.trim()) issues.push({ step: 0, field: "title", message: "عنوان آزمون را وارد کنید." }); if (!draft.description.trim()) issues.push({ step: 0, field: "description", message: "یک توضیح کوتاه برای آزمون وارد کنید." }); if (draft.settings.durationMinutes < 5) issues.push({ step: 1, field: "duration", message: "مدت آزمون باید حداقل ۵ دقیقه باشد." }); if (!draft.questions.length) issues.push({ step: 2, field: "questions", message: "حداقل یک سؤال به آزمون اضافه کنید." }); draft.questions.forEach((question, index) => { if (!question.stem.trim()) issues.push({ step: 2, field: `question-${question.id}`, message: `متن سؤال ${toPersianNumber(index + 1)} کامل نشده است.` }); if (question.type === "single_choice" && (!question.correctOptionId || question.options.some((option) => !option.label.trim()))) issues.push({ step: 2, field: `question-${question.id}`, message: `گزینه‌ها یا پاسخ درست سؤال ${toPersianNumber(index + 1)} کامل نیست.` }); if (question.type === "multiple_choice" && (!question.correctOptionIds?.length || question.options.some((option) => !option.label.trim()))) issues.push({ step: 2, field: `question-${question.id}`, message: `گزینه‌ها یا پاسخ‌های درست سؤال ${toPersianNumber(index + 1)} کامل نیست.` }); }); if (!draft.schedule.startAt || !draft.schedule.endAt || new Date(draft.schedule.endAt) <= new Date(draft.schedule.startAt)) issues.push({ step: 3, field: "schedule", message: "زمان پایان باید بعد از زمان شروع باشد." }); return issues; }
function Field({ label, required, error, children }: { label: string; required?: boolean; error?: string; children: React.ReactNode }) { return <label className="block text-sm font-bold"><span>{label}{required && <span className="mr-1 text-destructive">*</span>}</span><div className="mt-2">{children}</div>{error && <span className="mt-1.5 block text-xs font-bold text-destructive">{error}</span>}</label>; }
function Counter({ value, max }: { value: number; max: number }) { return <span className="mt-1 block text-left text-[10px] font-bold text-muted-foreground">{toPersianNumber(value)} / {toPersianNumber(max)}</span>; }
function SettingSwitch({ label, description, checked, onChange }: { label: string; description: string; checked: boolean; onChange: (checked: boolean) => void }) { return <div className="flex items-center justify-between gap-4 rounded-2xl border p-4"><div><p className="text-sm font-extrabold">{label}</p><p className="mt-1 text-xs leading-5 text-muted-foreground">{description}</p></div><button type="button" role="switch" aria-checked={checked} onClick={() => onChange(!checked)} className={cn("relative h-6 w-11 shrink-0 rounded-full transition-colors", checked ? "bg-primary" : "bg-muted")}><span className={cn("absolute top-1 h-4 w-4 rounded-full bg-white shadow transition-transform", checked ? "right-6" : "right-1")}/></button></div>; }
function BuilderSkeleton() { return <div className="grid gap-6 xl:grid-cols-[250px_1fr]"><div className="h-64 animate-soft-pulse rounded-2xl bg-muted"/><div className="h-[620px] animate-soft-pulse rounded-2xl bg-muted"/></div>; }
