"use client";

import Link from "next/link";
import { motion } from "framer-motion";
import { ArrowLeft, BadgeCheck, BarChart3, BookOpenCheck, Check, ChevronLeft, Clock3, FileCheck2, GraduationCap, Menu, PlayCircle, ShieldCheck, Sparkles, UsersRound, X } from "lucide-react";
import { useState } from "react";
import { Logo } from "@/components/shared/logo";
import { ThemeToggle } from "@/components/shared/theme-toggle";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";

const fade = { hidden: { opacity: 0, y: 14 }, visible: { opacity: 1, y: 0 } };
export default function LandingPage() {
  const [open, setOpen] = useState(false);
  const nav = <nav className="flex items-center gap-1"><a href="#features" className="rounded-lg px-3 py-2 text-sm font-bold text-muted-foreground hover:text-foreground">قابلیت‌ها</a><a href="#experience" className="rounded-lg px-3 py-2 text-sm font-bold text-muted-foreground hover:text-foreground">تجربه آزمون</a><a href="#security" className="rounded-lg px-3 py-2 text-sm font-bold text-muted-foreground hover:text-foreground">امنیت</a></nav>;
  return <div className="overflow-hidden bg-background"><header className="sticky top-0 z-40 border-b border-border/65 bg-background/80 backdrop-blur-xl"><div className="mx-auto flex h-[72px] max-w-7xl items-center justify-between px-4 sm:px-6"><Logo/><div className="hidden md:block">{nav}</div><div className="flex items-center gap-1.5"><ThemeToggle/><Button asChild variant="ghost" className="hidden sm:inline-flex"><Link href="/login">ورود</Link></Button><Button asChild className="hidden sm:inline-flex"><Link href="/register">شروع رایگان<ArrowLeft className="h-4 w-4"/></Link></Button><Button variant="ghost" size="icon" className="md:hidden" onClick={() => setOpen(!open)} aria-label="منو">{open ? <X/> : <Menu/>}</Button></div></div>{open && <div className="border-t bg-card px-4 py-3 md:hidden">{nav}<div className="mt-2 grid grid-cols-2 gap-2"><Button asChild variant="secondary"><Link href="/login">ورود</Link></Button><Button asChild><Link href="/register">شروع رایگان</Link></Button></div></div>}</header>
    <main>
      <section className="relative"><div className="soft-grid absolute inset-0 -z-10 opacity-40 [mask-image:linear-gradient(to_bottom,black,transparent)]"/><div className="absolute -right-40 top-10 -z-10 h-96 w-96 rounded-full bg-indigo-400/15 blur-3xl"/><div className="absolute -left-48 top-32 -z-10 h-96 w-96 rounded-full bg-teal-400/10 blur-3xl"/><div className="mx-auto grid max-w-7xl items-center gap-12 px-4 py-16 sm:px-6 md:py-24 lg:grid-cols-[1.04fr_.96fr] lg:py-28"><motion.div initial="hidden" animate="visible" variants={{ visible: { transition: { staggerChildren: .1 } } }}><motion.div variants={fade} className="inline-flex items-center gap-2 rounded-full border bg-card/85 px-3 py-1.5 text-xs font-extrabold text-primary shadow-soft"><Sparkles className="h-3.5 w-3.5"/>ارزیابی دیجیتال، دقیق و انسانی</motion.div><motion.h1 variants={fade} className="mt-6 max-w-2xl text-4xl font-black leading-[1.25] tracking-tight sm:text-5xl lg:text-6xl">هر آزمون، فرصتی برای <span className="text-primary">یادگیری بهتر</span> است.</motion.h1><motion.p variants={fade} className="mt-6 max-w-xl text-base leading-8 text-muted-foreground sm:text-lg">Examora فضای آزمون آنلاین مدارس را با تجربه‌ای آرام برای دانش‌آموزان و ابزارهایی دقیق برای آموزگاران، دوباره طراحی می‌کند.</motion.p><motion.div variants={fade} className="mt-8 flex flex-col gap-3 sm:flex-row"><Button asChild size="lg"><Link href="/register">ساخت فضای مدرسه <ArrowLeft className="h-4 w-4"/></Link></Button><Button asChild size="lg" variant="outline"><Link href="#experience"><PlayCircle className="h-4 w-4"/> مشاهده تجربه آزمون</Link></Button></motion.div><motion.div variants={fade} className="mt-8 flex flex-wrap gap-x-5 gap-y-2 text-xs font-bold text-muted-foreground"><span className="flex items-center gap-1.5"><Check className="h-4 w-4 text-emerald-500"/>راه‌اندازی سریع</span><span className="flex items-center gap-1.5"><Check className="h-4 w-4 text-emerald-500"/>کاملاً فارسی و راست‌چین</span><span className="flex items-center gap-1.5"><Check className="h-4 w-4 text-emerald-500"/>بدون نیاز به کارت بانکی</span></motion.div></motion.div>
        <motion.div initial={{ opacity: 0, scale: .96, x: -12 }} animate={{ opacity: 1, scale: 1, x: 0 }} transition={{ duration: .55, delay: .1 }} className="relative mx-auto w-full max-w-xl"><div className="absolute -inset-5 -z-10 rounded-[2.5rem] bg-gradient-to-br from-indigo-500/20 via-violet-500/10 to-teal-400/20 blur-2xl"/><Card className="overflow-hidden rounded-3xl border-white/60 bg-card/95 shadow-lift dark:border-border"><div className="flex items-center justify-between border-b px-5 py-4"><div className="flex gap-1.5" dir="ltr"><i className="h-2.5 w-2.5 rounded-full bg-rose-400"/><i className="h-2.5 w-2.5 rounded-full bg-amber-400"/><i className="h-2.5 w-2.5 rounded-full bg-emerald-400"/></div><span className="rounded-lg bg-emerald-500/10 px-2 py-1 text-[11px] font-bold text-emerald-600">آزمون در حال برگزاری</span></div><div className="p-5 sm:p-7"><div className="flex items-center justify-between"><div><p className="text-xs text-muted-foreground">زیست‌شناسی · دوازدهم</p><h2 className="mt-1 text-lg font-black">آزمون جامع زیست‌شناسی</h2></div><div className="rounded-xl bg-amber-500/10 px-3 py-2 text-sm font-black text-amber-600">۴۲:۱۸</div></div><div className="mt-6 flex items-center justify-between text-xs font-bold"><span>سؤال ۳ از ۲۰</span><span className="text-primary">۱۵٪ تکمیل شده</span></div><Progress value={15} className="mt-2"/><div className="mt-6 rounded-2xl border bg-surface p-4"><p className="text-sm font-bold leading-7">کدام اندامک مسئول تولید بخش عمدهٔ انرژی مورد نیاز سلول است؟</p><div className="mt-4 grid gap-2">{["هسته", "میتوکندری", "ریبوزوم"].map((item, index) => <div key={item} className={`flex items-center gap-3 rounded-xl border px-3 py-2.5 text-xs font-bold ${index === 1 ? "border-primary bg-primary/5 text-primary" : "bg-card"}`}><span className={`grid h-5 w-5 place-items-center rounded-full border text-[10px] ${index === 1 ? "border-primary bg-primary text-white" : ""}`}>{["الف", "ب", "ج"][index]}</span>{item}</div>)}</div></div><div className="mt-5 flex justify-between"><Button variant="outline" size="sm">سؤال قبل</Button><Button size="sm">ثبت و ادامه <ChevronLeft className="h-3.5 w-3.5"/></Button></div></div></Card><div className="absolute -bottom-6 -right-5 rounded-2xl border bg-card p-3.5 shadow-lift"><div className="flex items-center gap-2"><div className="rounded-xl bg-teal-500/10 p-2 text-teal-600"><BadgeCheck className="h-5 w-5"/></div><div><p className="text-xs font-extrabold">پاسخ‌ها محفوظ‌اند</p><p className="text-[10px] text-muted-foreground">آخرین ذخیره: همین حالا</p></div></div></div></motion.div></div></section>
      <section className="border-y bg-card/50"><div className="mx-auto grid max-w-7xl grid-cols-2 gap-y-6 px-4 py-8 sm:grid-cols-4 sm:px-6"><Metric value="۹۸٪" label="رضایت مدارس"/><Metric value="+۴۵هزار" label="آزمون موفق"/><Metric value="۳ دقیقه" label="میانگین راه‌اندازی"/><Metric value="۲۴/۷" label="پایداری سرویس"/></div></section>
      <section id="features" className="mx-auto max-w-7xl px-4 py-20 sm:px-6"><div className="max-w-2xl"><p className="section-label">طراحی‌شده برای جریان واقعی مدرسه</p><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-4xl">همه‌چیز برای یک ارزیابی بهتر، در یک فضای منسجم</h2><p className="mt-4 leading-7 text-muted-foreground">از ساخت سؤال تا تحلیل نتایج؛ Examora پیچیدگی‌های روز آزمون را از مسیر شما برمی‌دارد.</p></div><div className="mt-10 grid gap-4 md:grid-cols-3"><Feature icon={BookOpenCheck} title="تجربه آزمون متمرکز" text="رابطی آرام، سازگار با موبایل و طراحی‌شده برای تمرکز دانش‌آموز."/><Feature icon={UsersRound} title="مدیریت آسان کلاس‌ها" text="آزمون‌ها، دانش‌آموزان و زمان‌بندی را بدون پیچیدگی مدیریت کنید."/><Feature icon={BarChart3} title="بینش‌های قابل اقدام" text="عملکرد کلاس و هر دانش‌آموز را با گزارش‌های روشن بهتر بشناسید."/></div></section>
      <section id="experience" className="bg-slate-950 py-20 text-white dark:bg-slate-900"><div className="mx-auto grid max-w-7xl gap-10 px-4 sm:px-6 lg:grid-cols-2 lg:items-center"><div><p className="section-label text-indigo-300">تجربه دانش‌آموز</p><h2 className="mt-3 text-3xl font-black leading-tight sm:text-4xl">در لحظه‌ای که مهم است، فقط سؤال و دانش‌آموز.</h2><p className="mt-5 max-w-xl leading-8 text-slate-300">تایمر همیشه در دسترس است، وضعیت پاسخ‌ها روشن است و جابه‌جایی میان سؤال‌ها بدون حواس‌پرتی انجام می‌شود؛ روی موبایل هم به همان اندازه خوب.</p><ul className="mt-7 space-y-3 text-sm text-slate-200">{["پشتیبانی از سؤال‌های تستی و تشریحی", "نشان‌دار کردن سؤال‌ها برای مرور", "کنترل کامل زمان و روند پیشرفت"].map((item) => <li key={item} className="flex items-center gap-2"><Check className="h-4 w-4 text-teal-300"/>{item}</li>)}</ul><Button asChild variant="secondary" className="mt-8"><Link href="/register">ساخت حساب و شروع آزمون <ArrowLeft className="h-4 w-4"/></Link></Button></div><div className="rounded-3xl border border-white/10 bg-white/[.06] p-4 shadow-2xl backdrop-blur-sm"><div className="rounded-2xl bg-white p-5 text-slate-900 sm:p-6"><div className="flex items-center justify-between border-b pb-4"><div><p className="text-[11px] font-bold text-slate-500">آزمون جامع زیست‌شناسی</p><p className="mt-1 text-sm font-black">سؤال ۷ از ۲۰</p></div><Clock3 className="h-5 w-5 text-indigo-600"/></div><div className="py-6"><p className="font-bold leading-7">نقش اصلی غشای پلاسمایی در سلول چیست؟</p><div className="mt-5 grid gap-2">{["تنظیم ورود و خروج مواد", "تولید پروتئین", "ذخیره اطلاعات ژنتیکی"].map((item, i) => <div key={item} className={`rounded-xl border p-3 text-xs font-bold ${i === 0 ? "border-indigo-500 bg-indigo-50 text-indigo-700" : "border-slate-200"}`}>{item}</div>)}</div></div><div className="flex items-center justify-between border-t pt-4 text-xs font-bold text-slate-500"><span>۶ پاسخ ثبت شده</span><span className="text-indigo-600">ذخیره امن</span></div></div></div></div></section>
      <section className="mx-auto grid max-w-7xl gap-10 px-4 py-20 sm:px-6 lg:grid-cols-[.9fr_1.1fr] lg:items-center"><div className="order-2 grid grid-cols-2 gap-3 lg:order-1"><MiniManagement icon={FileCheck2} label="ساخت آزمون" value="۵ گام ساده"/><MiniManagement icon={GraduationCap} label="مشارکت کلاس" value="۲۸ از ۳۰ نفر"/><MiniManagement icon={BarChart3} label="میانگین کلاس" value="۷۶.۴٪"/><MiniManagement icon={Clock3} label="زمان‌سنج هوشمند" value="دقیق و شفاف"/></div><div className="order-1 lg:order-2"><p className="section-label">فضای کار آموزگار</p><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-4xl">کنترل حرفه‌ای، بدون پیچیدگی اضافه</h2><p className="mt-5 leading-8 text-muted-foreground">آزمون را مرحله‌به‌مرحله بسازید، بانک سؤال خود را رشد دهید و با نتایجی که واقعاً قابل فهم هستند، برای جلسهٔ بعدی تصمیم بگیرید.</p><Button asChild variant="outline" className="mt-7"><Link href="/teacher/dashboard">نمایش داشبورد آموزگار <ArrowLeft className="h-4 w-4"/></Link></Button></div></section>
      <section id="security" className="mx-4 mb-20 rounded-3xl bg-gradient-to-br from-indigo-600 to-violet-700 px-6 py-14 text-white sm:mx-6 sm:px-10 lg:mx-auto lg:max-w-7xl"><div className="grid gap-8 lg:grid-cols-[1.1fr_.9fr] lg:items-center"><div><div className="inline-flex rounded-xl bg-white/15 p-2.5"><ShieldCheck className="h-6 w-6"/></div><h2 className="mt-5 text-3xl font-black">اعتماد، بخشی از طراحی ماست.</h2><p className="mt-4 max-w-xl leading-8 text-indigo-100">از ذخیرهٔ دوره‌ای پاسخ‌ها تا کنترل شفاف وضعیت آزمون، زیرساخت تجربه‌ای قابل‌اعتماد برای مدرسه فراهم شده است.</p></div><div className="grid gap-3 sm:grid-cols-2">{["ذخیرهٔ مطمئن پاسخ‌ها", "رویدادهای قابل پیگیری", "دسترسی بر پایه نقش", "نمایش شفاف وضعیت"].map((item) => <div key={item} className="rounded-2xl border border-white/15 bg-white/10 p-4 text-sm font-bold"><Check className="mb-3 h-4 w-4 text-teal-200"/>{item}</div>)}</div></div></section>
      <section className="mx-auto max-w-3xl px-4 pb-20 text-center"><p className="section-label">آماده برای شروع</p><h2 className="mt-3 text-3xl font-black sm:text-4xl">ارزیابی را به تجربه‌ای بهتر تبدیل کنید.</h2><p className="mx-auto mt-4 max-w-xl leading-7 text-muted-foreground">فضای مدرسهٔ خود را در چند دقیقه بسازید و اولین آزمون را با آرامش برگزار کنید.</p><Button asChild size="lg" className="mt-7"><Link href="/register">شروع با Examora <ArrowLeft className="h-4 w-4"/></Link></Button></section>
    </main><footer className="border-t bg-card"><div className="mx-auto flex max-w-7xl flex-col gap-4 px-4 py-8 text-xs text-muted-foreground sm:flex-row sm:items-center sm:justify-between sm:px-6"><Logo/><p>© ۲۰۲۶ Examora · طراحی‌شده برای آموزش بهتر</p><div className="flex gap-4"><a href="#" className="hover:text-foreground">حریم خصوصی</a><a href="#" className="hover:text-foreground">پشتیبانی</a></div></div></footer>
  </div>;
}
function Metric({ value, label }: { value: string; label: string }) { return <div className="text-center"><p className="text-2xl font-black text-primary sm:text-3xl">{value}</p><p className="mt-1 text-xs font-bold text-muted-foreground">{label}</p></div>; }
function Feature({ icon: Icon, title, text }: { icon: typeof BookOpenCheck; title: string; text: string }) { return <Card className="group p-6 transition-all hover:-translate-y-1 hover:shadow-lift"><div className="inline-flex rounded-2xl bg-primary/10 p-3 text-primary transition-transform group-hover:scale-105"><Icon className="h-6 w-6"/></div><h3 className="mt-5 font-black">{title}</h3><p className="mt-2 text-sm leading-7 text-muted-foreground">{text}</p></Card>; }
function MiniManagement({ icon: Icon, label, value }: { icon: typeof BookOpenCheck; label: string; value: string }) { return <Card className="p-4 sm:p-5"><Icon className="h-5 w-5 text-primary"/><p className="mt-6 text-lg font-black">{value}</p><p className="mt-1 text-xs font-bold text-muted-foreground">{label}</p></Card>; }
